---
# suse-ses-prepare_admin_node/tasks/main.yml

- name: "Install salt-master and salt-minion packages"
  package:
    name: "{{ admin_node_salt_packages }}"

- name: "Start the salt services"
  service:
    name: "{{ item }}" 
    state: "started"
    enabled: "true"
  with_items:
    - "{{ admin_node_salt_services }}"

- name: "Install deepsea packages"
  package:
    name: "{{ admin_node_deepsea_packages }}"

- name: "Create the directory /srv/pillar/ceph/stack/ceph/"
  file:
    path: "/srv/pillar/ceph/stack/ceph/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Create /srv/pillar/ceph/stack/ceph/cluster.yml from template"
  template:
    src: "srv_pillar_ceph_stack_ceph_cluster.yml.j2"
    dest: "/srv/pillar/ceph/stack/ceph/cluster.yml"
    owner: "root"
    group: "root"
    mode: "0644"
