---
# suse-ses-prepare_admin_node/tasks/main.yml

- name: "Install salt-master and salt-minion packages"
  package:
    name: "{{ admin_node_salt_packages }}"

- name: "Start the salt services"
  service:
    name: "{{ item }}" 
    state: "started"
    enabled: "true"
  with_items:
    - "{{ admin_node_salt_services }}"

- name: "Install deepsea packages"
  package:
    name: "{{ admin_node_deepsea_packages }}"

- name: "Install additional packages"
  package:
    name: "{{ admin_node_additional_packages }}"

- name: "Create the directory /srv/pillar/ceph/stack/ceph/"
  file:
    path: "/srv/pillar/ceph/stack/ceph/"
    state: "directory"
    owner: "salt"
    group: "salt"
    mode: "0755"

- name: "Create /srv/pillar/ceph/stack/ceph/cluster.yml from template"
  template:
    src: "srv_pillar_ceph_stack_ceph_cluster.yml.j2"
    dest: "/srv/pillar/ceph/stack/ceph/cluster.yml"
    owner: "salt"
    group: "salt"
    mode: "0644"

- name: "Create /srv/pillar/ceph/master_minion.sls from template"
  template:
    src: "srv_pillar_ceph_master_minion.sls.j2"
    dest: "/srv/pillar/ceph/master_minion.sls"
    owner: "salt"
    group: "salt"
    mode: "0644"

- name: "Create the directory /srv/pillar/ceph/proposals/"
  file:
    path: "/srv/pillar/ceph/proposals/"
    state: "directory"
    owner: "salt"
    group: "salt"
    mode: "0755"

- name: "Create /srv/pillar/ceph/proposals/policy.cfg from template"
  template:
    src: "srv_pillar_ceph_proposals_policy.cfg.j2"
    dest: "/srv/pillar/ceph/proposals/policy.cfg"
    owner: "salt"
    group: "salt"
    mode: "0644"

- include_tasks: ntp_sles12.yml
  when: ansible_distribution == "SLES" and ansible_distribution_major_version == "12"
